### ISSUE TITLE
Border disappears when floating in sway

### ISSUE THREAD

**Issue by lephe** [emersion/hello-wayland#11]
This is more of a curiosity than a real issue, I guess. I've noticed while programming my own client application that the border set by sway disappears when making the window float and tile back. And funnily enough, it also occurs in this simple program.

This is a direct consequence of a change in the xdg_toplevel events received by the application. For instance, on my desktop with 1-pixel-wide borders on all sides, this happens:

```
# Initially:
xdg_toplevel.configure: width=634 height=1049 states=activated,4,5,6,7
# After floating and tiling back:
xdg_toplevel.configure: width=636 height=1051 states=activated,4,5,6,7
````
The only actual difference in the window's properties (at least in what's reported by `get_tree`) is the `window_rect`:
```
# Initially:
"rect": { "x": 1280, "y": 425, "width": 636, "height": 1051 },
"window_rect": { "x": 1, "y": 1, "width": 634, "height": 1049 },
# After floating and tiling back:
"rect": { "x": 1280, "y": 425, "width": 636, "height": 1051 },
"window_rect": { "x": 0, "y": 0, "width": 636, "height": 1051 },
```
I can more or less understand what's going on, since the toplevel's window rectangle is not the same thing as the buffer rectangle (for decorations, drop shadows and so on). But I can't seem to find the proper way to obtain that information and configure the window as to preserve the borders.

Any hints about this?

**Comment by emersion** [comment]
This would be a Sway issue.

**Comment by lephe** [comment]
Thanks, I [posted it here](https://github.com/swaywm/sway/issues/5066). I also noticed the `border` attribute changes to `none` (not sure how I missed it) so it's definitely sway.
