### ISSUE TITLE
README doesn't mention ImageMagick dependency / Makefile fails to check if ImageMagick installed

### ISSUE THREAD

**Issue by chris03-dev** [emersion/hello-wayland#15]
This is rather self-explanatory:
Makefile runs the `convert` command without any conditions whatsoever.

I'd like to propose one of these solutions:
1. Add a condition before the `convert` command, checking if ImageMagick is installed in the Makefile (sorry, I'm not very familiar with the `make` build tool)
2. Inform users that ImageMagick is a dependency for this repository.

Thanks for reading.

**Comment by emersion** [comment]
I'd rather keep it simple and not add checks to the Makefile. After all, we don't have checks for other deps either.

Patches welcome to add deps to the README.
