### ISSUE TITLE
failed to create display

### ISSUE THREAD

**Issue by directorscut82** [emersion/hello-wayland#5]
Hi,
when i try to run the client i get a "failed to create display". Inspecting the code path i think connect_to_socket returns NULL (also i didn't set any environment variable WAYLAND_SOCKET or WAYLAND_DISPLAY).. Maybe this is a setup/configuration issue?

by the way weston compiles & runs without issues

(ubuntu 16.04/latest wayland)

**Comment by emersion** [comment]
You need to start the app from within a Wayland session (e.g. from within Weston). `WAYLAND_DISPLAY` needs to be set.

**Comment by directorscut82** [comment]
I thought that only the older example needed to be run explicitly within weston (which runs successfully by the way & thank you for providing an easier gateway to understanding wayland). 

When i run the same thing with the XDG_* example i get a "no wl_shm, wl_compositor or xdg_base support" error and i assumed that maybe i should run it from my (non-wayland) ubuntu session. I dont really know if it is related to the fact that i also get compilation errors when building with gcc (instead of clang)

**Comment by directorscut82** [comment]
thank you for the clarification:)
