### ISSUE TITLE
wl_surface.commit should be sent after xdg_surface.ack_configure

### ISSUE THREAD

**Issue by michaelforney** [emersion/hello-wayland#8]
I noticed that hello-wayland responds to xdg_surface.configure with an ack_configure, but does not send wl_surface.commit after this.

I wasn't sure if this was valid client behavior, so I consulted the spec, and it seems to suggest that ack_configure should only be sent before a surface commit:

> When a configure event is received, if a client commits the
> surface in response to the configure event, then the client
> must make an ack_configure request sometime before the commit
> request, passing along the serial of the configure event.

This says that if a client commits, it should send ack_configure before the commit. I'm not sure if this first "if" should be read as "if and only if", but since the spec doesn't describe any other situations in which ack_configure should be sent, this is how I'm interpreting it.

> A client is not required to commit immediately after sending
> an ack_configure request - it may even ack_configure several times
> before its next surface commit.

"not required to commit *immediately*" seems to imply that it *is* required to commit at some point.

**Comment by emersion** [comment]
Maybe we should just send a commit without attaching a new buffer

**Comment by michaelforney** [comment]
Yes, I think that should work.
